// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["bailian"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeArrayValue,
  createLazyFacadeObjectValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "bailian",
    artifactBasename: "api.js",
  });
}
export const BAILIAN_BASE_URL: FacadeModule["BAILIAN_BASE_URL"] =
  loadFacadeModule()["BAILIAN_BASE_URL"];
export const BAILIAN_DEFAULT_COST: FacadeModule["BAILIAN_DEFAULT_COST"] =
  createLazyFacadeObjectValue(
    () => loadFacadeModule()["BAILIAN_DEFAULT_COST"] as object,
  ) as FacadeModule["BAILIAN_DEFAULT_COST"];
export const BAILIAN_MODEL_CATALOG: FacadeModule["BAILIAN_MODEL_CATALOG"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["BAILIAN_MODEL_CATALOG"] as unknown as readonly unknown[],
  ) as FacadeModule["BAILIAN_MODEL_CATALOG"];
export const buildBailianModelDefinition: FacadeModule["buildBailianModelDefinition"] = ((
  ...args
) =>
  loadFacadeModule()["buildBailianModelDefinition"](
    ...args,
  )) as FacadeModule["buildBailianModelDefinition"];
export const buildBailianProvider: FacadeModule["buildBailianProvider"] = ((...args) =>
  loadFacadeModule()["buildBailianProvider"](...args)) as FacadeModule["buildBailianProvider"];
